name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: write # for checkout and publishing a GitHub release
  id-token: write # for generating NPM provenance

jobs:
  release:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js ðŸš€
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup npmrc ðŸ”
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install dependencies ðŸ“¦
        run: npm install

      - name: Test Setup ðŸ§ª
        run: npx lerna run build

      - name: Run tests ðŸ§ª
        run: npm test

      - name: Upload coverage report ðŸ“Š
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Configure Git ðŸ› 
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Publish ðŸš€
        run: npx lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
